name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          ðŸ‘‹ Thanks for opening your first issue in OurProject!
          
          To help us help you, please include:
          - A clear description of the issue
          - Steps to reproduce (if applicable)
          - Your environment details (OS, version, etc.)
          
          We'll get back to you soon!
        pr-message: |
          ðŸŽ‰ Welcome and thank you for your first contribution to OurProject!
          
          A maintainer will review your changes shortly. In the meantime:
          - Make sure all CI checks pass
          - Update the documentation if needed
          - Add yourself to the contributors list (optional)
          
          Thanks for helping improve the project!
